spring.datasource.url=jdbc:postgresql://pg-2b20c255-sekretowicz-pet-project.b.aivencloud.com:25554/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_NrHLBRBR6BtYMW0w7gy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true