server:
  port: 8080

spring:
  application:
    name: gym-crm

  datasource:
    url: jdbc:postgresql://pg-2b20c255-sekretowicz-pet-project.b.aivencloud.com:25554/defaultdb
    username: avnadmin
    password: AVNS_NrHLBRBR6BtYMW0w7gy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true

  doc:
    swagger-ui:
      path: /swagger-ui

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    feign: DEBUG
    feign.client: DEBUG